function [colheaders,data]=func_import_OUTPUT(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 08-Feb-2016 10:43:31

% Import the file
newData1 = importdata(fileToRead1);
colheaders = newData1.colheaders;
data = newData1.data;

end

