function vel_grad_mat = func_deriv_voring(X_CP,Y_CP,Z_CP,vortex_ring,GAMMA)
       
    if vortex_ring.Z_SIGN == -1
       GAMMA = - GAMMA;
    end
    
    [dudx_val1,dudy_val1,dudz_val1,dvdx_val1,dvdy_val1,dvdz_val1,dwdx_val1,dwdy_val1,dwdz_val1] ...
        = func_deriv_vortexl(X_CP,Y_CP,Z_CP,vortex_ring.X_1,vortex_ring.Y_1,vortex_ring.Z_1,...
        vortex_ring.X_2,vortex_ring.Y_2,vortex_ring.Z_2,GAMMA);
    
    [dudx_val2,dudy_val2,dudz_val2,dvdx_val2,dvdy_val2,dvdz_val2,dwdx_val2,dwdy_val2,dwdz_val2] ...
        = func_deriv_vortexl(X_CP,Y_CP,Z_CP,vortex_ring.X_2,vortex_ring.Y_2,vortex_ring.Z_2,...
        vortex_ring.X_4,vortex_ring.Y_4,vortex_ring.Z_4,GAMMA);
  
    [dudx_val3,dudy_val3,dudz_val3,dvdx_val3,dvdy_val3,dvdz_val3,dwdx_val3,dwdy_val3,dwdz_val3] ...
        = func_deriv_vortexl(X_CP,Y_CP,Z_CP,vortex_ring.X_4,vortex_ring.Y_4,vortex_ring.Z_4,...
        vortex_ring.X_3,vortex_ring.Y_3,vortex_ring.Z_3,GAMMA);
    
    [dudx_val4,dudy_val4,dudz_val4,dvdx_val4,dvdy_val4,dvdz_val4,dwdx_val4,dwdy_val4,dwdz_val4] ...
        = func_deriv_vortexl(X_CP,Y_CP,Z_CP,vortex_ring.X_4,vortex_ring.Y_4,vortex_ring.Z_4,...
        vortex_ring.X_1,vortex_ring.Y_1,vortex_ring.Z_1,GAMMA);
  
    

vel_grad_mat = [dudx_val1+dudx_val2+dudx_val3+dudx_val4,dudy_val1+dudy_val2+dudy_val3+dudy_val4,dudz_val1+dudz_val2+dudz_val3+dudz_val4;...
                dvdx_val1+dvdx_val2+dvdx_val3+dvdx_val4,dvdy_val1+dvdy_val2+dvdy_val3+dvdy_val4,dvdz_val1+dvdz_val2+dvdz_val3+dvdz_val4;...
                dwdx_val1+dwdx_val2+dwdx_val3+dwdx_val4,dwdy_val1+dwdy_val2+dwdy_val3+dwdy_val4,dwdz_val1+dwdz_val2+dwdz_val3+dwdz_val4];
        
end