function [yc,xx]=import_airfoil_geometry(fileToRead1,M)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 09-Feb-2016 10:07:27

% Import the file
rawData1 = importdata(fileToRead1);

%% X,Y coordinates 

x = rawData1(:,1);
y = rawData1(:,2);

%% Thick mesh for interpolation 

for  i=1:M
    
 theta=((i-1)*pi)/(M-1);
 xx(i)=0.5*(1-cos(theta));
 
end

%% To split the airfoil into a lower and a upper part

N=find(x==0,1);
k1=1;
l1=1;

for k=N:-1:1
    yupper(k1)=y(k);
    xupper(k1)=x(k);
    k1=k1+1;
end

for l=N:length(x)
    ylower(l1)=y(l);
    xlower(l1)=x(l);
    l1=l1+1;
end

%% To interpolate values of the coordinates on the same mesh 

ylow = interp1(xlower,ylower,xx);
yup  = interp1(xupper,yupper,xx);

%% To compute camber line

yc=(ylow+yup)/2;

end

